import { createClient } from "https://esm.sh/@supabase/supabase-js@2.112.3";
const supabase=createClient("https://uspndiasqerdypsfqofl.supabase.co","sb_publishable_pakYKjwYUZ5VbmEMV6k-vQ_mNw-Caik");
const $=s=>document.querySelector(s);
const state={session:null,profile:null,projects:[],steps:[],logs:[],attachments:[],calendarDate:new Date(),openId:null,view:"dashboard"};
const roleLabels={engineering:"Gestor de Engenharia",production:"Gestor de Produção",designer:"Projetista",boilerworks:"Caldeiraria",mechanical:"Mecânica",electrical:"Elétrica",maintenance:"Manutenção · visualização",director:"Diretoria · visualização",admin:"Administrador · acesso total"};
const areaLabels={designer:"Projeto",boilerworks:"Caldeiraria",mechanical:"Mecânica",electrical:"Elétrica"};
const stageLabels={pending_approval:"Aguardando aprovação",awaiting_estimate:"Aguardando estimativa",workflow:"Em fluxo",rejected:"Recusado"};
const flowStatuses=["Aprovado","Aguardando início","Em desenvolvimento","Aguardando informações","Em validação","Concluído"];
const workerRoles=["designer","boilerworks","mechanical","electrical"];
const sectors=[["01","Prensa"],["02","Fornos"],["03","Rodo de Moldagem"],["04","Mesa de Preparação para Barras"],["05","Laminador"],["06","Decapagem"],["07","Bobinador"],["08","Embalagem"],["09","Manutenção"],["10","Layouts"],["11","Utilidades"],["12","Lixador de Faces"],["50","Trefila"]];
const disciplines=[["ELE","Elétrica · 01"],["MEC","Mecânica · 02"],["CIV","Civil · 03"],["CAL","Caldeiraria · 04"],["USI","Usinagem · 05"],["TRE","Trefila · 06"]];
const acceptedFiles={"application/pdf":"pdf","image/jpeg":"jpg","image/png":"png","image/webp":"webp"};
const role=()=>state.profile?.role;
const canOrder=()=>["engineering","production","designer","admin"].includes(role());
const canEdit=()=>["engineering","production","admin"].includes(role());
const isManager=()=>["engineering","production","admin"].includes(role());
const isWorker=()=>workerRoles.includes(role());
const canWorkProject=p=>role()==="admin"||(isWorker()&&p.current_area===role());
const canAttach=()=>["engineering","production",...workerRoles,"admin"].includes(role());
const esc=(v="")=>String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[c]);
const today=()=>new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10);
const dateBR=d=>d?new Intl.DateTimeFormat("pt-BR").format(new Date(`${d}T12:00:00`)):"—";
const dateTimeBR=d=>new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(d));
const projectCode=id=>`PRJ-${String(id).padStart(4,"0")}`;
const areaBadge=a=>`<span class="area-badge area-${esc(a)}">${esc(areaLabels[a]||a)}</span>`;
function toast(m,e=false){const x=$("#toast");x.textContent=m;x.className=`toast show${e?" error":""}`;clearTimeout(toast.timer);toast.timer=setTimeout(()=>x.className="toast",3500)}
function setBusy(b,on,label="Aguarde…"){if(!b)return;if(on){b.dataset.label=b.textContent;b.textContent=label;b.disabled=true}else{b.textContent=b.dataset.label||b.textContent;b.disabled=false}}
function errorMessage(e,f="Não foi possível concluir a operação."){toast(e?.message||f,true)}
function priorityClass(p){return p==="Crítica"?"critical":p==="Alta"?"high":""}

function pendingProjects(){
  if(role()==="admin")return state.projects.filter(p=>["pending_approval","awaiting_estimate"].includes(p.stage));
  if(["engineering","production"].includes(role()))return state.projects.filter(p=>p.stage==="pending_approval");
  if(role()==="designer")return state.projects.filter(p=>p.stage==="awaiting_estimate"||(p.stage==="workflow"&&p.current_area==="designer"&&p.status!=="Concluído"));
  if(isWorker())return state.projects.filter(p=>p.stage==="workflow"&&p.current_area===role()&&p.status!=="Concluído");
  return [];
}

async function submitRequest(form,dialog=null){
  const b=form.querySelector('[type="submit"],button[value="default"]'),fileInput=form.elements.files,files=fileInput?[...fileInput.files]:[];
  if(files.length>5)return toast("Envie no máximo 5 arquivos.",true);
  if(files.some(f=>!acceptedFiles[f.type]))return toast("Use somente PDF, JPG, PNG ou WEBP.",true);
  if(files.some(f=>f.size>8388608))return toast("Cada arquivo deve ter no máximo 8 MB.",true);
  setBusy(b,true,"Enviando…");const d=Object.fromEntries(new FormData(form));
  const{data,error}=await supabase.rpc("fluxo_submit_request",{p_title:d.title,p_requester:d.requester||"",p_area:d.area||"",p_description:d.description,p_impact:d.impact||"",p_priority:d.priority,p_due_date:d.due_date});
  if(error){setBusy(b,false);return errorMessage(error)}
  const failures=await uploadRequestFiles(data,files);setBusy(b,false);form.reset();form.querySelector('[name="priority"]').value="Média";dialog?.close();
  toast(failures?`Solicitação criada, mas ${failures} arquivo(s) não puderam ser anexados.`:state.session?"Projeto e arquivos enviados para estimativa.":"Solicitação e arquivos enviados para revisão.",Boolean(failures));if(state.session)await loadData();
}
async function uploadRequestFiles(request,files){if(!files.length)return 0;let failures=0;for(const file of files){const ext=acceptedFiles[file.type],path=`${request.id}/${request.upload_token}/${crypto.randomUUID()}.${ext}`;const upload=await supabase.storage.from("fluxo-project-pdfs").upload(path,file,{contentType:file.type});if(upload.error){failures++;continue}const meta=await supabase.from("fluxo_attachments").insert({project_id:request.id,object_path:path,file_name:file.name,size_bytes:file.size,mime_type:file.type,uploaded_by:state.session?.user?.id||null});if(meta.error){failures++;await supabase.storage.from("fluxo-project-pdfs").remove([path])}}return failures}
async function loadData(){const[pr,sr,lr,ar]=await Promise.all([supabase.from("fluxo_projects").select("*").order("position").order("created_at"),supabase.from("fluxo_project_steps").select("*").order("created_at"),supabase.from("fluxo_logs").select("*").order("created_at",{ascending:false}),supabase.from("fluxo_attachments").select("*").order("created_at",{ascending:false})]);if(pr.error)return errorMessage(pr.error,"Não foi possível atualizar os projetos.");if(sr.error)return errorMessage(sr.error,"Não foi possível carregar as etapas dos setores.");state.projects=pr.data||[];state.steps=sr.data||[];state.logs=lr.data||[];state.attachments=ar.data||[];render()}

function render(){const workflow=state.projects.filter(p=>p.stage==="workflow"),pending=pendingProjects();const stats=[["Total em aberto",workflow.filter(p=>p.status!=="Concluído").length,"dashboard"],["Alta ou crítica",workflow.filter(p=>["Alta","Crítica"].includes(p.priority)&&p.status!=="Concluído").length,"dashboard"],["Na sua área",workflow.filter(p=>canWorkProject(p)&&p.status!=="Concluído").length,"kanban"],["Ações pendentes",pending.length,"pending"]];$("#stats").innerHTML=stats.map(([l,n,v])=>`<button class="stat" data-stat-view="${v}"><span>${l}</span><b>${n}</b></button>`).join("");document.querySelectorAll("[data-stat-view]").forEach(b=>b.onclick=()=>switchView(b.dataset.statView));$("#pendingBadge").textContent=pending.length;$("#pendingBadge").classList.toggle("hidden",!pending.length);$("#pendingNav").classList.toggle("hidden",!["engineering","production",...workerRoles,"admin"].includes(role()));$("#alertBox").classList.toggle("hidden",!pending.length);$("#alertBox").innerHTML=pending.length?`<button class="alert-action" id="openPending"><b>${pending.length} ${pending.length===1?"ação pendente":"ações pendentes"}.</b> Clique para abrir a lista →</button>`:"";$("#openPending")?.addEventListener("click",()=>switchView("pending"));renderQueue();renderPending();renderKanban();renderCalendar()}
function queueProjects(){const q=$("#searchInput").value.trim().toLowerCase(),f=$("#stageFilter").value;return state.projects.filter(p=>(f?p.stage===f:p.stage==="workflow")&&(!q||[p.title,p.requester,p.area,areaLabels[p.current_area],projectCode(p.id)].join(" ").toLowerCase().includes(q)))}
function renderQueue(){const ps=queueProjects();$("#dragHint").classList.toggle("hidden",!canOrder());const header=`<div class="queue-header"><span>Ordem</span><span>Projeto / solicitação</span><span>Prioridade</span><span>Status</span><span>Vencimento</span><span>Horas</span><span>Progresso</span><span>Ações</span></div>`;$("#projectList").innerHTML=ps.length?header+ps.map(queueRow).join(""):`<div class="empty"><b>Nenhum projeto encontrado.</b><br>As demandas liberadas aparecerão aqui.</div>`;wireProjectButtons();setupDragging()}
function queueRow(p){const drag=canOrder()&&p.stage==="workflow";return`<article class="project-card" draggable="${drag}" data-id="${p.id}"><div class="drag-handle" title="Arrastar"><span>☷</span><b class="order-number">${p.position}</b></div><div class="project-main"><h3>${esc(p.title)}</h3><p>#${projectCode(p.id)} · ${esc(p.requester||"Solicitante não informado")} · ${esc(p.area||"Setor não informado")}</p><div class="project-tags">${areaBadge(p.current_area)}${p.drawing_code?`<small>Desenho ${esc(p.drawing_discipline)} · ${esc(p.drawing_code)}</small>`:""}</div></div><span class="pill ${priorityClass(p.priority)}">${esc(p.priority)}</span><span class="status-pill">${esc(p.status)}</span><div class="queue-value">${dateBR(p.due_date)}</div><div class="queue-value"><b>${p.estimated_hours||"—"}h</b></div><div class="queue-progress"><div><i style="width:${p.progress}%"></i></div><b>${p.progress}%</b></div><button class="open-project" data-id="${p.id}" title="Editar ou visualizar">✎</button></article>`}
function setupDragging(){let dragged=null;document.querySelectorAll('.project-card[draggable="true"]').forEach(card=>{card.ondragstart=()=>{dragged=card;card.classList.add("dragging")};card.ondragend=async()=>{card.classList.remove("dragging");if(!dragged)return;dragged=null;await saveOrder()};card.ondragover=e=>{e.preventDefault();if(!dragged||card===dragged)return;const box=card.getBoundingClientRect();card.parentNode.insertBefore(dragged,e.clientY<box.top+box.height/2?card:card.nextSibling)}})}
async function saveOrder(){const visible=[...document.querySelectorAll('.project-card[draggable="true"]')].map(el=>Number(el.dataset.id));if(!visible.length)return;const ordered=[...state.projects.filter(p=>p.stage==="workflow")].sort((a,b)=>a.position-b.position),set=new Set(visible);let cursor=0;const ids=ordered.map(p=>set.has(p.id)?visible[cursor++]:p.id);const results=await Promise.all(ids.map((id,i)=>supabase.from("fluxo_projects").update({position:i+1}).eq("id",id)));if(results.some(r=>r.error))return toast("Não foi possível salvar a nova ordem.",true);toast("Ordem numérica atualizada.");await loadData()}

function renderPending(){const items=pendingProjects();let title="Ações pendentes";if(["engineering","production"].includes(role()))title="Aprovações pendentes";else if(role()==="designer")title="Pendências do projetista";else if(isWorker())title=`Pendências da ${areaLabels[role()]}`;$("#pendingTitle").textContent=title;$("#pendingList").innerHTML=items.length?items.map(p=>`<article class="pending-card"><div><span class="pill ${priorityClass(p.priority)}">${esc(p.priority)}</span> ${p.stage==="workflow"?areaBadge(p.current_area):""}<h3>${esc(p.title)}</h3><p>${esc(p.requester||"Solicitante não informado")}${p.area?` · ${esc(p.area)}`:""}</p><p>${esc(p.description)}</p><small>Prazo: ${dateBR(p.due_date)} · ${stageLabels[p.stage]||p.status}</small></div><button class="button primary open-project" data-id="${p.id}">${p.stage==="pending_approval"?"Revisar":p.stage==="awaiting_estimate"?"Informar horas":"Abrir atividade"}</button></article>`).join(""):`<div class="empty"><b>Nenhuma ação pendente.</b><br>Você está em dia.</div>`;wireProjectButtons()}
function renderKanban(){const cols=[["Fila / aguardando",["Aprovado","Aguardando início","Aguardando informações"]],["Em execução",["Em desenvolvimento"]],["Validação",["Em validação"]],["Concluídos",["Concluído"]]],flow=state.projects.filter(p=>p.stage==="workflow");$("#kanbanBoard").innerHTML=cols.map(([title,statuses])=>{const items=flow.filter(p=>statuses.includes(p.status));return`<section class="kanban-column"><div class="kanban-column-head"><span>${title}</span><b>${items.length}</b></div><div class="kanban-stack">${items.length?items.map(kanbanCard).join(""):`<div class="kanban-empty">Vazio</div>`}</div></section>`}).join("");wireProjectButtons();document.querySelectorAll(".advance-project").forEach(b=>b.onclick=()=>advanceProject(Number(b.dataset.id)))}
function kanbanCard(p){const next=nextStatus(p.status),advance=canAdvanceProject(p);return`<article class="kanban-card area-card-${p.current_area}">${areaBadge(p.current_area)} <span class="pill ${priorityClass(p.priority)}">${esc(p.priority)}</span><h3>${esc(p.title)}</h3><p>#${projectCode(p.id)} · ${esc(p.area||"Área não informada")}</p><p>${dateBR(p.due_date)} · ${p.estimated_hours||"—"}h</p>${p.drawing_code?`<p><b>${esc(p.drawing_discipline)} · ${esc(p.drawing_code)}</b></p>`:""}<div class="kanban-actions"><button class="open-project" data-id="${p.id}">✎ Abrir</button>${advance?`<button class="advance advance-project" data-id="${p.id}">${next==="Concluído"&&p.current_area==="designer"?"✓ Codificar e concluir":"▶ Avançar fase"}</button>`:""}</div></article>`}
function nextStatus(s){return{"Aprovado":"Em desenvolvimento","Aguardando início":"Em desenvolvimento","Aguardando informações":"Em desenvolvimento","Em desenvolvimento":"Em validação","Em validação":"Concluído"}[s]||null}
function canAdvanceProject(p){return Boolean(nextStatus(p.status)&&canWorkProject(p))}
async function advanceProject(id){const p=state.projects.find(x=>x.id===id),next=p&&nextStatus(p.status);if(!next)return;if(next==="Concluído"&&p.current_area==="designer"){openProject(id);return toast("Preencha a codificação para concluir o desenho.")}const progress={"Em desenvolvimento":25,"Em validação":75,"Concluído":100}[next]||p.progress;const{error}=await supabase.rpc("fluxo_update_current_step",{p_project_id:id,p_estimated_hours:p.estimated_hours,p_due_date:p.due_date,p_status:next,p_progress:progress});if(error)return errorMessage(error);toast(`Atividade movida para “${next}”.`);await loadData()}
function wireProjectButtons(){document.querySelectorAll(".open-project").forEach(b=>b.onclick=()=>openProject(Number(b.dataset.id)))}

function field(label,name,value,type="text",options="",disabled=false,span=false){const cls=span?' class="span-2"':'';if(type==="textarea")return`<label${cls}>${label}<textarea name="${name}" rows="3" ${disabled?"disabled":""}>${esc(value)}</textarea></label>`;if(type==="select")return`<label${cls}>${label}<select name="${name}" ${disabled?"disabled":""}>${options}</select></label>`;return`<label${cls}>${label}<input name="${name}" type="${type}" value="${esc(value??"")}" ${disabled?"disabled":""}></label>`}
function sectorOptionsHTML(selected="",codesOnly=false){return`<option value="">Selecione</option>`+sectors.map(([code,name])=>`<option value="${codesOnly?code:`${code} - ${name}`}" ${(codesOnly?code:`${code} - ${name}`)===selected?"selected":""}>${code} - ${name}</option>`).join("")}
function openProject(id){const p=state.projects.find(x=>x.id===id);if(!p)return;state.openId=id;const editable=canEdit()&&p.stage!=="rejected";$("#projectModalOverline").innerHTML=`#${projectCode(p.id)} · ${stageLabels[p.stage]} ${p.stage==="workflow"?areaBadge(p.current_area):""}`;$("#projectModalTitle").textContent=p.title;$("#projectFields").innerHTML=field("Título","title",p.title,"text","",!editable,true)+field("Solicitante","requester",p.requester,"text","",!editable)+field("Setor","area",p.area,"select",sectorOptionsHTML(p.area),!editable)+field("Descrição","description",p.description,"textarea","",!editable,true)+field("Impacto","impact",p.impact,"textarea","",!editable,true)+field("Prioridade","priority",p.priority,"select",["Baixa","Média","Alta","Crítica"].map(v=>`<option ${v===p.priority?"selected":""}>${v}</option>`).join(""),!editable)+field("Prazo atual","due_date",p.due_date,"date","",!editable);$("#projectSaveBtn").classList.toggle("hidden",!editable);$("#projectSaveBtn").textContent=p.stage==="pending_approval"?"Revisar e aprovar":"Salvar alterações";$("#deleteProjectBtn").classList.toggle("hidden",!canEdit());$("#projectExtra").innerHTML=extrasTemplate(p);wireExtras(p);$("#projectDialog").showModal()}
function nextDrawingSequence(code){return Math.min(999,Math.max(0,...state.projects.filter(p=>p.drawing_sector_code===code).map(p=>p.drawing_sequence||0))+1)}
function drawingTemplate(p){if(role()!=="designer"||p.current_area!=="designer"||p.stage!=="workflow"||!["Em validação","Concluído"].includes(p.status))return"";const sector=p.drawing_sector_code||(p.area.match(/^(\d{2})/)?.[1]||""),sequence=p.drawing_sequence||nextDrawingSequence(sector),year=p.drawing_year??(new Date().getFullYear()%100);return`<div class="detail-block drawing-block"><h3>${p.status==="Concluído"?"Codificação do desenho":"Concluir e codificar desenho"}</h3><p>Formato: setor.sequencial.revisão-ano.folha/total. Somente o projetista pode alterar.</p><form id="drawingForm" class="form-grid"><label>Classificação<select name="drawing_discipline" required><option value="">Selecione</option>${disciplines.map(([code,name])=>`<option value="${code}" ${p.drawing_discipline===code?"selected":""}>${code} - ${name}</option>`).join("")}</select></label><label>Setor do desenho<select name="drawing_sector_code" required>${sectorOptionsHTML(sector,true)}</select></label><label>Sequencial<input name="drawing_sequence" type="number" min="1" max="999" required value="${sequence}"></label><label>Revisão<input name="drawing_revision" type="number" min="0" max="99" required value="${p.drawing_revision??0}"></label><label>Ano<input name="drawing_year" type="number" min="0" max="99" required value="${year}"></label><label>Folha<input name="drawing_sheet" type="number" min="1" max="999" required value="${p.drawing_sheet||1}"></label><label>Total de folhas<input name="drawing_total_sheets" type="number" min="1" max="999" required value="${p.drawing_total_sheets||1}"></label><div class="drawing-preview span-2">Código atual: <b>${esc(p.drawing_code||"será gerado ao concluir")}</b></div><div class="span-2"><button class="button primary" type="submit">${p.status==="Concluído"?"Atualizar codificação":"Concluir e gerar código"}</button></div></form></div>`}
function transferTemplate(p){if(p.stage!=="workflow"||p.status!=="Concluído"||!canWorkProject(p))return"";const options=Object.entries(areaLabels).filter(([key])=>key!==p.current_area).map(([key,label])=>`<option value="${key}">${label}</option>`).join("");return`<div class="detail-block transfer-block"><h3>Encaminhar para outra área</h3><p>A transferência é direta e não passa por nova aprovação dos gestores.</p><form id="transferForm" class="form-grid"><label>Destino<select name="target_area" required><option value="">Selecione</option>${options}</select></label><label>Horas previstas<input name="hours" type="number" min="1" required></label><label>Prazo de conclusão<input name="due_date" type="date" min="${today()}" required></label><label>Orientação para a próxima área<input name="note" maxlength="500" placeholder="Opcional"></label><div class="span-2"><button class="button primary" type="submit">Enviar diretamente para a área</button></div></form></div>`}
function historyTemplate(p){const steps=state.steps.filter(s=>s.project_id===p.id);return`<div class="detail-block"><h3>Histórico de áreas e prazos</h3><div class="step-history">${steps.length?steps.map((s,i)=>`<div class="step-item ${s.status}"><b>${i+1}. ${esc(areaLabels[s.area])}</b><span>${s.estimated_hours}h · até ${dateBR(s.due_date)} · ${s.progress}%</span><small>${s.status==="completed"?"Etapa concluída":"Etapa atual"}</small></div>`).join(""):`<small>O histórico começa quando o projetista informa a estimativa.</small>`}</div></div>`}
function extrasTemplate(p){
  const logs=state.logs.filter(l=>l.project_id===p.id),files=state.attachments.filter(a=>a.project_id===p.id);
  const estimate=["designer","admin"].includes(role())&&p.stage==="awaiting_estimate"?`<div class="detail-block action-highlight"><h3>Horas previstas para desenvolvimento do projeto</h3><p>O projeto somente entra na fila após esta informação.</p><form id="estimateForm" class="inline-form"><input name="hours" type="number" min="1" required placeholder="Ex.: 16"><button class="button primary" type="submit">Liberar no fluxo</button></form></div>`:"";
  const reject=isManager()&&p.stage==="pending_approval"?`<div class="detail-block rejection-block"><h3>Recusar solicitação</h3><form id="rejectForm"><label>Motivo da recusa *<textarea name="reason" required minlength="3" maxlength="1000" rows="3" placeholder="Explique por que o projeto foi recusado."></textarea></label><button class="button danger" type="submit">Confirmar recusa</button></form></div>`:"";
  const rejection=p.stage==="rejected"?`<div class="detail-block rejection-reason"><h3>Motivo da recusa</h3><p>${esc(p.rejection_reason||"Motivo não registrado em solicitações antigas.")}</p></div>`:"";
  const responsible=p.stage==="workflow"&&canWorkProject(p),statuses=p.current_area==="designer"?flowStatuses.filter(v=>v!=="Concluído"||p.status==="Concluído"):flowStatuses;
  const status=responsible?`<div class="detail-block"><h3>Planejamento e andamento da ${esc(areaLabels[p.current_area])}</h3><form id="statusForm" class="form-grid"><label>Status<select name="status">${statuses.map(v=>`<option ${v===p.status?"selected":""}>${v}</option>`).join("")}</select></label><label>Progresso (%)<input name="progress" type="number" min="0" max="100" value="${p.progress}"></label><label>Horas previstas<input name="hours" type="number" min="1" value="${p.estimated_hours||""}" required></label><label>Prazo de conclusão<input name="due_date" type="date" value="${p.due_date}" required></label><div class="span-2 phase-actions"><button class="button ghost" type="submit">Atualizar planejamento</button>${canAdvanceProject(p)?`<button id="advanceModal" class="button primary" type="button">${nextStatus(p.status)==="Concluído"&&p.current_area==="designer"?"✓ Codificar e concluir":"▶ Passar de fase"}</button>`:""}</div></form></div>`:"";
  const logForm=responsible?`<form id="logForm" class="inline-form"><input name="message" maxlength="1000" required placeholder="Informação aguardada ou próxima etapa"><button class="button primary" type="submit">Adicionar</button></form>`:"";
  const fileForm=canAttach()?`<form id="attachmentForm" class="inline-form optional-upload"><input name="file" type="file" accept="application/pdf,image/jpeg,image/png,image/webp,.pdf,.jpg,.jpeg,.png,.webp"><button class="button ghost" type="submit">Anexar arquivo</button></form><small>Opcional · PDF, JPG, PNG ou WEBP de até 8 MB.</small>`:"";
  return`${estimate}${reject}${rejection}${status}${drawingTemplate(p)}${transferTemplate(p)}<div class="detail-block"><h3>Planejamento atual</h3><p>${areaBadge(p.current_area)} <b>${p.estimated_hours?`${p.estimated_hours} hora(s) previstas`:"Horas ainda não informadas"}</b> · ${esc(p.status)} · ${p.progress}% · prazo ${dateBR(p.due_date)}</p>${p.drawing_code?`<p class="drawing-code"><b>${esc(p.drawing_discipline)} · ${esc(p.drawing_code)}</b></p>`:""}</div>${historyTemplate(p)}<div class="detail-block"><h3>Acompanhamento</h3>${logForm}<div class="log-list">${logs.length?logs.map(l=>`<div class="log-item">${esc(l.message)}<small>${esc(l.author_name)} · ${dateTimeBR(l.created_at)}</small></div>`).join(""):`<small>Nenhum registro.</small>`}</div></div><div class="detail-block"><h3>Imagens e PDFs</h3>${fileForm}<div class="attachment-list">${files.length?files.map(a=>`<button type="button" class="attachment-item open-file" data-path="${esc(a.object_path)}">${a.mime_type?.startsWith("image/")?"🖼️":"📄"} ${esc(a.file_name)}</button>`).join(""):`<small>Nenhum arquivo anexado. Isso não impede o avanço do projeto.</small>`}</div></div>`;
}

function wireExtras(p){
  $("#estimateForm")?.addEventListener("submit",async e=>{e.preventDefault();const form=e.currentTarget,b=form.querySelector("button"),hours=Number(new FormData(form).get("hours"));if(!hours||hours<1)return toast("Informe uma quantidade válida de horas.",true);setBusy(b,true,"Liberando…");const{error}=await supabase.from("fluxo_projects").update({estimated_hours:hours,stage:"workflow"}).eq("id",p.id);setBusy(b,false);if(error)return errorMessage(error);toast("Estimativa registrada. Projeto liberado no fluxo do projetista.");$("#projectDialog").close();switchView("dashboard");await loadData()});
  $("#rejectForm")?.addEventListener("submit",async e=>{e.preventDefault();const form=e.currentTarget,b=form.querySelector("button"),reason=String(new FormData(form).get("reason")||"").trim();if(reason.length<3)return toast("Informe o motivo da recusa.",true);setBusy(b,true,"Recusando…");const{error}=await supabase.from("fluxo_projects").update({stage:"rejected",status:"Recusado",rejection_reason:reason}).eq("id",p.id);setBusy(b,false);if(error)return errorMessage(error);toast("Solicitação recusada com o motivo registrado.");$("#projectDialog").close();await loadData()});
  $("#statusForm")?.addEventListener("submit",async e=>{e.preventDefault();const form=e.currentTarget,b=form.querySelector('[type="submit"]'),d=Object.fromEntries(new FormData(form));setBusy(b,true,"Atualizando…");const{error}=await supabase.rpc("fluxo_update_current_step",{p_project_id:p.id,p_estimated_hours:Number(d.hours),p_due_date:d.due_date,p_status:d.status,p_progress:Number(d.progress)});setBusy(b,false);if(error)return errorMessage(error);toast("Planejamento e andamento atualizados.");$("#projectDialog").close();await loadData()});
  $("#advanceModal")?.addEventListener("click",async()=>{$("#projectDialog").close();await advanceProject(p.id)});
  $("#drawingForm")?.addEventListener("submit",async e=>{e.preventDefault();const form=e.currentTarget,b=form.querySelector("button"),d=Object.fromEntries(new FormData(form));if(Number(d.drawing_sheet)>Number(d.drawing_total_sheets))return toast("A folha atual não pode ser maior que o total de folhas.",true);setBusy(b,true,"Gerando código…");const payload={status:"Concluído",progress:100,drawing_discipline:d.drawing_discipline,drawing_sector_code:d.drawing_sector_code,drawing_sequence:Number(d.drawing_sequence),drawing_revision:Number(d.drawing_revision),drawing_year:Number(d.drawing_year),drawing_sheet:Number(d.drawing_sheet),drawing_total_sheets:Number(d.drawing_total_sheets)};const{data,error}=await supabase.from("fluxo_projects").update(payload).eq("id",p.id).select("drawing_code").single();setBusy(b,false);if(error)return errorMessage(error);toast(`Desenho concluído: ${data.drawing_code}. Agora pode encaminhar para outra área.`);$("#projectDialog").close();await loadData()});
  $("#transferForm")?.addEventListener("submit",async e=>{e.preventDefault();const form=e.currentTarget,b=form.querySelector("button"),d=Object.fromEntries(new FormData(form));setBusy(b,true,"Transferindo…");const{error}=await supabase.rpc("fluxo_transfer_project",{p_project_id:p.id,p_target_area:d.target_area,p_estimated_hours:Number(d.hours),p_due_date:d.due_date,p_note:d.note||""});setBusy(b,false);if(error)return errorMessage(error);toast(`Projeto enviado diretamente para ${areaLabels[d.target_area]}.`);$("#projectDialog").close();await loadData()});
  $("#logForm")?.addEventListener("submit",async e=>{e.preventDefault();const message=new FormData(e.currentTarget).get("message");const{error}=await supabase.from("fluxo_logs").insert({project_id:p.id,message,author_id:state.session.user.id,author_name:state.profile.display_name});if(error)return errorMessage(error);toast("Registro adicionado.");await loadData();openProject(p.id)});
  $("#attachmentForm")?.addEventListener("submit",async e=>{e.preventDefault();const file=new FormData(e.currentTarget).get("file");if(!file||!file.size)return toast("Selecione um arquivo ou continue sem anexar.",true);const ext=acceptedFiles[file.type];if(!ext)return toast("Use somente PDF, JPG, PNG ou WEBP.",true);if(file.size>8388608)return toast("O arquivo deve ter no máximo 8 MB.",true);const path=`${p.id}/${crypto.randomUUID()}.${ext}`,upload=await supabase.storage.from("fluxo-project-pdfs").upload(path,file,{contentType:file.type});if(upload.error)return errorMessage(upload.error);const meta=await supabase.from("fluxo_attachments").insert({project_id:p.id,object_path:path,file_name:file.name,size_bytes:file.size,mime_type:file.type,uploaded_by:state.session.user.id});if(meta.error){await supabase.storage.from("fluxo-project-pdfs").remove([path]);return errorMessage(meta.error)}toast("Arquivo anexado.");await loadData();openProject(p.id)});
  document.querySelectorAll(".open-file").forEach(b=>b.onclick=async()=>{const{data,error}=await supabase.storage.from("fluxo-project-pdfs").createSignedUrl(b.dataset.path,120);if(error)return errorMessage(error);window.open(data.signedUrl,"_blank","noopener")});
}

async function deleteOpenProject(){const p=state.projects.find(x=>x.id===state.openId);if(!p||!canEdit())return;if(!confirm(`Excluir definitivamente o projeto “${p.title}”?`))return;const b=$("#deleteProjectBtn");setBusy(b,true,"Excluindo…");const{error}=await supabase.from("fluxo_projects").delete().eq("id",p.id);setBusy(b,false);if(error)return errorMessage(error);toast("Projeto excluído.");$("#projectDialog").close();await loadData()}
function calendarEntries(){const entries=state.steps.map(s=>{const p=state.projects.find(x=>x.id===s.project_id);return p&&p.stage!=="rejected"?{project:p,date:s.due_date,area:s.area,hours:s.estimated_hours,status:s.status}:null}).filter(Boolean);for(const p of state.projects.filter(p=>p.stage!=="rejected"&&!state.steps.some(s=>s.project_id===p.id)))entries.push({project:p,date:p.due_date,area:"designer",hours:p.estimated_hours,status:"pending"});return entries}
function renderCalendar(){const d=state.calendarDate,y=d.getFullYear(),m=d.getMonth();$("#calendarTitle").textContent=new Intl.DateTimeFormat("pt-BR",{month:"long",year:"numeric"}).format(d);const first=new Date(y,m,1),start=new Date(y,m,1-first.getDay()),entries=calendarEntries(),cells=[];for(let i=0;i<42;i++){const day=new Date(start);day.setDate(start.getDate()+i);const iso=[day.getFullYear(),String(day.getMonth()+1).padStart(2,"0"),String(day.getDate()).padStart(2,"0")].join("-");const items=entries.filter(e=>e.date===iso);cells.push(`<div class="day ${day.getMonth()!==m?"muted":""}"><b>${day.getDate()}</b>${items.map(e=>`<button class="calendar-project calendar-${e.area} open-project" data-id="${e.project.id}" title="${esc(areaLabels[e.area])} · ${e.hours||"—"}h">${esc(e.project.title)}<small>${esc(areaLabels[e.area])}</small></button>`).join("")}</div>`)}$("#calendarGrid").innerHTML=cells.join("");wireProjectButtons()}
function switchView(view){state.view=view;["dashboard","pending","kanban","calendar"].forEach(n=>$(`#${n}View`).classList.toggle("hidden",n!==view));$("#stats").classList.toggle("hidden",view==="calendar");document.querySelectorAll(".nav-item[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===view));const copy={dashboard:["Fila de execução","Prioridades, responsáveis, horas, prazos e progresso em uma única visão."],pending:["Aprovações e pendências","Conclua as ações da sua área para o projeto avançar."],kanban:["Quadro de atividades","Acompanhe cada projeto ao longo do fluxo entre as áreas."],calendar:["Calendário de todos os prazos","Azul: Projeto · Verde: Mecânica · Laranja: Caldeiraria · Roxo: Elétrica."]};$("#pageTitle").textContent=copy[view][0];$("#pageSubtitle").textContent=copy[view][1]}
async function establishSession(session){state.session=session;if(!session){state.profile=null;$("#publicView").classList.remove("hidden");$("#appView").classList.add("hidden");$("#loginBtn").classList.remove("hidden");$("#logoutBtn").classList.add("hidden");$("#userBadge").classList.add("hidden");return}const{data,error}=await supabase.from("fluxo_profiles").select("*").eq("user_id",session.user.id).single();if(error||!data){await supabase.auth.signOut();return toast("Este usuário não possui acesso ao sistema.",true)}state.profile=data;$("#publicView").classList.add("hidden");$("#appView").classList.remove("hidden");$("#loginBtn").classList.add("hidden");$("#logoutBtn").classList.remove("hidden");$("#userBadge").classList.remove("hidden");$("#userBadge").textContent=data.display_name;$("#roleTitle").textContent=roleLabels[data.role];$("#newInternalBtn").classList.toggle("hidden",!["engineering","production","designer","admin"].includes(data.role));switchView("dashboard");await loadData()}

$("#requestForm").addEventListener("submit",e=>{e.preventDefault();submitRequest(e.currentTarget)});
$("#internalForm").addEventListener("submit",e=>{e.preventDefault();submitRequest(e.currentTarget,$("#newDialog"))});
$("#loginBtn").onclick=()=>$("#loginDialog").showModal();
$("#logoutBtn").onclick=async()=>{const{error}=await supabase.auth.signOut();if(error)return errorMessage(error);await establishSession(null);toast("Sessão encerrada.")};
$("#loginForm").addEventListener("submit",async e=>{e.preventDefault();const form=e.currentTarget,b=form.querySelector(".primary"),d=Object.fromEntries(new FormData(form)),u=d.username.trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"");setBusy(b,true,"Entrando…");const{error}=await supabase.auth.signInWithPassword({email:`${u}@fluxo.local`,password:d.password});setBusy(b,false);if(error)return toast("Usuário ou senha inválidos.",true);form.reset();$("#loginDialog").close()});
$("#projectForm").addEventListener("submit",async e=>{e.preventDefault();const p=state.projects.find(x=>x.id===state.openId);if(!p||!canEdit())return;const form=e.currentTarget,b=$("#projectSaveBtn"),d=Object.fromEntries(new FormData(form)),payload={title:d.title,requester:d.requester||"",area:d.area||"",description:d.description,impact:d.impact||"",priority:d.priority,due_date:d.due_date};if(p.stage==="pending_approval")payload.stage="awaiting_estimate";setBusy(b,true,p.stage==="pending_approval"?"Aprovando…":"Salvando…");const{error}=await supabase.from("fluxo_projects").update(payload).eq("id",p.id);setBusy(b,false);if(error)return errorMessage(error);toast(p.stage==="pending_approval"?"Projeto revisado e enviado para estimativa.":"Projeto atualizado.");$("#projectDialog").close();await loadData()});
$("#deleteProjectBtn").onclick=deleteOpenProject;$("#projectCloseBtn").onclick=()=>$("#projectDialog").close();$("#projectCloseX").onclick=()=>$("#projectDialog").close();$("#newInternalBtn").onclick=()=>$("#newDialog").showModal();$("#refreshBtn").onclick=loadData;$("#searchInput").oninput=renderQueue;$("#stageFilter").onchange=renderQueue;document.querySelectorAll(".nav-item[data-view]").forEach(b=>b.onclick=()=>switchView(b.dataset.view));$("#prevMonth").onclick=()=>{state.calendarDate=new Date(state.calendarDate.getFullYear(),state.calendarDate.getMonth()-1,1);renderCalendar()};$("#nextMonth").onclick=()=>{state.calendarDate=new Date(state.calendarDate.getFullYear(),state.calendarDate.getMonth()+1,1);renderCalendar()};document.querySelectorAll('input[type="date"]').forEach(i=>i.min=today());
supabase.auth.onAuthStateChange((_event,session)=>setTimeout(()=>establishSession(session),0));const{data:{session}}=await supabase.auth.getSession();await establishSession(session);
